#!/bin/bash

# using host cert for both FE and pilot
voms-proxy-init -cert /etc/grid-security/hostcert.pem -key /etc/grid-security/hostkey.pem -out /tmp/proxy.new -hours 72 -voms osg:/osg/ligo && \
chown frontend:frontend /tmp/proxy.new && \
mv /tmp/proxy.new /tmp/vo_proxy

voms-proxy-init -cert /etc/grid-security/pilotCerts/pilot-cert.pem -key /etc/grid-security/pilotCerts/pilot-key.pem -out /tmp/pilot_proxy.new -hours 72 -voms osg:/osg/ligo && \
chown frontend:frontend /tmp/pilot_proxy.new && \
mv /tmp/pilot_proxy.new /tmp/pilot_proxy
